language: node_js
deploy:
  provider: heroku
  api_key:
    secure: ikQR1/yp+peElufXvmf1R1jYxJ+wUkQLDsSxrE7r7pUB8H9AtmivLFH0IykK/VLbRfQk0V8oygWZhzpJ6Cd/cRCFH7mcWDIRpZZ/Ks5yPSJk4aZSmc8GiEiqiuJz804x7aRsSZKJ5WbJYz7BiVfRqT8+f8dTmP0NVOes8jgAit4=
  app: whiskchat-server
  on:
    repo: WhiskTech/whiskchat-server
env:
  global:
  - secure: Hb4kaC/647AyjXzjvx56queFYeFrwEGLMyMzURPShIB7rUjPLm3AOcf5bOEEVTC1DkN1GZ53M0KHAvKEOJDmn3mB+dikmq4bi3evypHSzKOw2bwQ1fDPQuKgErqk9jfkehzgayzt/bL9TKh7cryVjV43ht9YGqb3AdBV0q4P/Qk=
  - secure: WaU+qNDQN3PJVRlxGbbg5RJpFNeq7dC5uh3JVQjgxZO5Ex/BgfIjmfriyFoW/fAB/6puDkqfydQsx/tjVbQ6X/QfGnsKVpmpamWAU8BcAW+mPBth74LERlQlOiN6ADD3oCHqjEX54mvPXx858ULAQ1E6iGXCKCI0w85d2QNmvOM=
scripts: node server.js travisci
services:
  - redis-server